use dbSblenders
select * from tbAgente
select * from tbCategoriaIngrediente
select * from tbCategoriaProduto
select * from tbClienteOnline
select * from tbEstadoPedido
select * from tbEstoqueIngrediente
select * from tbFuncionario
select * from tbInformacaoNutricional
select * from tbInformacaoNutricionalTipo
select * from tbIngrediente
select * from tbPedido
select * from tbPedidoProduto
select * from tbPedidoProdutoIngrediente
select * from tbProduto
select * from tbProdutoIngrediente
select * from tbRestaurante
select * from tbTipoAgente
select * from tbTipoFuncionario
select * from tbTotem